### ISSUE TITLE
Publish modules to npm 

### ISSUE THREAD

**Issue by salminio** [MeirionHughes/aurelia-resize#10]
Aurelia CLI seems to be solely reliant on npm and was hoping you could publish the latest set to npm

**Comment by MeirionHughes** [comment]
Sure; I'll try to get it done as soon as I'm able; needs a few other fixes too I think

**Comment by MeirionHughes** [comment]
I've pushed 0.4.1 to with the correct dependency; if it doesn't work I doubt I'll have time to fix it before I go on holiday on Friday. I will take another look when I get back.

**Comment by salminio** [comment]
D:\test>npm install aurelia-resize --save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "D:\Users\anon\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "aurelia-resize" "--save"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/aurelia-resize
npm ERR! 404
npm ERR! 404  'aurelia-resize' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\npm-debug.log
