### ISSUE TITLE
Update readme for webpack usage

### ISSUE THREAD

**Issue by rquast** [MeirionHughes/aurelia-resize#13]
In webpack, you need to add this to your package.json to get it to work.

  "aurelia": {
    "build": {
      "resources": [
        "aurelia-resize",
        "aurelia-resize/resizeable"
      ]
    }

Should I do a PR for this with the readme?

**Comment by MeirionHughes** [comment]
Please, I don't use webpack with aurelia so I'll defer to you.

**Comment by rquast** [comment]
Will do. :)
