### ISSUE TITLE
Resizable.js didn't transpile to ES5 properly 

### ISSUE THREAD

**Issue by rquast** [MeirionHughes/aurelia-resize#14]
Looks like resizeable.js didn't transpile 'let' to 'var' and 'class' in dist.

**Comment by rquast** [comment]
tsconfig.json has a target for es6, so it won't work in IE.

**Comment by MeirionHughes** [comment]
I've targeted es5 and assumed `Promise` and `Map` are both poly-filled. It is still common-js format though. published to 1.0.2. Give us a shout if that fixes the issue for you. 

If need be I can output to UMD module format.
