### ISSUE TITLE
Unexpected keyword 'const' and token ')'

### ISSUE THREAD

**Issue by jeffgrann** [MeirionHughes/aurelia-resize#15]
I'm getting the following errors:

`SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`

and after changing `const` and `let` to `var` in resizable.js, I'm getting:

`SyntaxError: Unexpected token ')'`

because of the arrow function assignment to this.callback.

So it looks like there may be some more transpiling issues.

**Comment by MeirionHughes** [comment]
> duplicate of #14

Hopefully 1.0.2 will fix this for es5 targets.

**Comment by jeffgrann** [comment]
Awesome!

**Comment by jeffgrann** [comment]
Works great now. Thanks!
