### ISSUE TITLE
Does not work in jspm

### ISSUE THREAD

**Issue by GabrielMancik** [MeirionHughes/aurelia-resize#17]
It seems that getting package with jspm automatically builds it if it finds build tasks in it. In new versions of aurelia-resize build tasks are missing making this plugin not usable in automated development environments.

**Comment by MeirionHughes** [comment]
I don't use jspm any more with aurelia; that said I was under the impression that `jspm install npm:aurelia-resize` installed everything, including `element-resize-detector`'s dependencies. Does that not work for you?

**Comment by GabrielMancik** [comment]
My package.json looks like this:
```
{
  "devDependencies": {
   ....
  },
  "aurelia": {
    "build": {
      "resources": [
        "aurelia-resize/resizeable"
      ]
    }
  },
  "jspm": {
    "dependencies": {
      ...
      "aurelia-resize": "npm:aurelia-resize@^1.0.2",
     ...
    "devDependencies": {}
  }
}
```
I get error: (404 Not Found) loading ../jspm_packages/npm/aurelia-resize@1.0.2/resizeable.js. Not sure why it is not looking inside dist folder.

**Comment by MeirionHughes** [comment]
Try it now.
