### ISSUE TITLE
1.0.3 has a breaking change regarding configuration

### ISSUE THREAD

**Issue by djensen47** [MeirionHughes/aurelia-resize#18]
This is a great project, thanks for all of the hard work!

I'm using this project in a javascript aurelia project.

I recently did an npm update, which pulled in 1.0.3, and, when loading the app, I started to get the following error:

```
DEBUG [aurelia] Loading plugin aurelia-resize.
Uncaught TypeError: Cannot read property '__useDefault' of undefined
```

So I dug around the node_modules dir for aurelia-resize. Turns out that the app has to be configured differently.

```
// old config
{
  "name": "aurelia-resize",
  "path": "../node_modules/aurelia-resize/dist",
  "main": "index"
},
{
  "name": "element-resize-detector",
  "path": "../node_modules/element-resize-detector/dist",
  "main": "element-resize-detector"
}
```

```
//new config
{
  "name": "aurelia-resize",
  "path": "../node_modules/aurelia-resize/dist/amd",
  "main": "index"
},
{
  "name": "element-resize-detector",
  "path": "../node_modules/element-resize-detector/dist",
  "main": "element-resize-detector"
}
```

Unfortunately, this was a minor patch release that resulted in a breaking change. I would recommend reverting 1.0.4 to match 1.0.2 and then release 1.0.3 as 1.1.0. Thoughts?

**Comment by MeirionHughes** [comment]
Sorry, that was my bad; the commonjs build wasn't even in the dist... try 1.0.4 with the old config. 

I think for 1.1.0 I'll produce a single file dist (bundle element-resize-detector) https://github.com/MeirionHughes/aurelia-resize/issues/19

**Comment by djensen47** [comment]
It happens. :wink:. Thanks for the quick turn around on this!

**Comment by MeirionHughes** [comment]
Is this working for you now btw?  You should be able to use either `/dist/amd`  or '/dist`

**Comment by djensen47** [comment]
Yes, it's working. Thanks!
