### ISSUE TITLE
Trying to use plugin and is not working

### ISSUE THREAD

**Issue by cdaniel77** [MeirionHughes/aurelia-resize#22]
I am using the CLI and did an

`npm install aurelia-resize --save`

I then added the following to my main.js:

```
aurelia.use
    .standardConfiguration()
    .feature('resources')
    .plugin('aurelia-resize');
```

I created two divs in my app.html

```
<div class="main">
  <div class="sidebar"></div>
  <div class="content" resizable resize.trigger($event.detail) & throttle:500></div>
</div>
```

In my app.js, I have the following:

```
export class App {
   resize(detail){
      console.log(detail);
   }
}
```

I then reload my page, and change the height of content in the console but nothing happens.

**Comment by MeirionHughes** [comment]
two issues there; 

- its resiz**e**able, not resizable (Queen's English please). :D  
- should pass a method to be your event handler - `resize.trigger="yourMethod($event.detail)"`

hopefully that resolves your issue.
