### ISSUE TITLE
Missing dependency to aurelia-pal

### ISSUE THREAD

**Issue by tipa** [MeirionHughes/aurelia-resize#23]
Had to manually install aurelia-pal for the plugin to throw no error on load.

**Comment by MeirionHughes** [comment]
balls... I have no luck with this repo - thanks for reporting.

**Comment by tipa** [comment]
Tried your package update v1.1.1, looks like the dependency still doesnt show up in my config.js
  
```
"npm:aurelia-resize@1.1.1": {
    "element-resize-detector": "npm:element-resize-detector@1.1.11"
},
```

**Comment by MeirionHughes** [comment]
ahh jspm... lets try again.
