### ISSUE TITLE
Upgrading to latest aurelia cli (1.0.0-beta.13) throws error loading element-resize-detector

### ISSUE THREAD

**Issue by salminio** [MeirionHughes/aurelia-resize#28]
I'm looking to update from aurelia-cli 0.26.1 to the latest (1.0.0-beta.13) and I hit an issue with the aurelia-resize dependency of element-resize-detector... As best I can tell the element-resize-detector is failing on a require statement inside the element-resize-detector.

//Detection strategies.
var objectStrategyMaker     = require('./detection-strategy/object');

with the following stacktrace
Unhandled rejection Error: Module name "detection-strategy/object" has not been loaded yet for context: _. Use require([])https://requirejs.org/docs/errors.html#notloaded    at makeError (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:3834:17)    at Object.localRequire [as require] (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:5102:44)    at requirejs (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:5463:24)    at o (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:56143:561)    at http://localhost:9000/scripts/vendor-bundle-8.5.0.js:56143:752    at Object.7../browser-detector (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:57242:31)    at o (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:56143:701)    at r (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:56143:867)    at http://localhost:9000/scripts/vendor-bundle-8.5.0.js:56143:896    at Object.execCb (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:5362:33)    at Module.check (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:4544:55)    at Module.enable (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:4842:22)    at Object.enable (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:5223:39)    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:4827:33)    at http://localhost:9000/scripts/vendor-bundle-8.5.0.js:3800:23    at each (http://localhost:9000/scripts/vendor-bundle-8.5.0.js:3725:31)

**Comment by 3cp** [comment]
ref: aurelia/cli#1054

**Comment by 3cp** [comment]
This can be closed. It was an aurelia-cli bug and it is fixed.
