### ISSUE TITLE
"Error: utils is not defined" after update to @0.3.0

### ISSUE THREAD

**Issue by jimnorth55** [MeirionHughes/aurelia-resize#5]
Version 0.2.0 was functioning without error.  Ran jspm install to update to 0.3.0 (no other changes), and am getting the following error.
# 

`system.src.js:4857 Uncaught (in promise) Error: utils is not defined
    Evaluating https://localhost:44382/jspm_packages/npm/element-resize-detector@1.1.0/dist/element-resize-detector.js
    Evaluating https://localhost:44382/jspm_packages/npm/element-resize-detector@1.1.0.js
    Error loading https://localhost:44382/jspm_packages/github/MeirionHughes/aurelia-resize@0.3.0.js
    at t (https://localhost:44382/jspm_packages/system.js:4:61)
    at g (https://localhost:44382/jspm_packages/system.js:4:9747)
    at https://localhost:44382/jspm_packages/system.js:4:9289
    at b (https://localhost:44382/jspm_packages/system.js:4:11045)
    at x (https://localhost:44382/jspm_packages/system.js:4:11393)
    at p (https://localhost:44382/jspm_packages/system.js:4:9271)
    at h (https://localhost:44382/jspm_packages/system.js:4:9656)
    at https://localhost:44382/jspm_packages/system.js:4:7925`

**Comment by MeirionHughes** [comment]
what version of jspm are you on? 0.16?

**Comment by jimnorth55** [comment]
Using JSPM 0.16.27

**Comment by MeirionHughes** [comment]
hmm I'm on 0.16.30 and its not complaining on install. That said, I'm bundling the app I tested this in. I will try in the skeleton app without bundling.

**Comment by MeirionHughes** [comment]
yeah reproduced it with the skeleton app. I thought I'd fixed that with the jspm override, but it seems it doesn't like it. I'll drop the release until I fix it.

**Comment by jimnorth55** [comment]
Thanks.  I appreciate your work in making this plugin available.

**Comment by MeirionHughes** [comment]
yeah sorry, it did work for me at the time, but I was bundling it. Without bundling its complaining about the dependency (which oddly is actually contained in the library). I'll try to resolve and re-release

**Comment by MeirionHughes** [comment]
right I think I've fixed it by embedding the library. Tested with the skeleton app and working. Can you confirm?

```
jspm uninstall aurelia-resize
jspm install aurelia-resize
```

**Comment by jimnorth55** [comment]
Looks good!  I think you've nailed it.   Thanks.

**Comment by MeirionHughes** [comment]
I'll try not to break it next time. :P
