### ISSUE TITLE
jspm dependency to npm:element-resize-detector 

### ISSUE THREAD

**Issue by MeirionHughes** [MeirionHughes/aurelia-resize#6]
I attempted to depend on the [npm:element-resize-detector](https://www.npmjs.com/package/element-resize-detector) library via a JSPM dependency. Unfortunately, even with a [shim](https://github.com/jspm/registry/pull/819), it results in an [error trying to resolve "utils"](https://github.com/MeirionHughes/aurelia-resize/issues/5). 

Temporarily fixed by embedding the minified distribution element-resize-detector into aurelia-resize.js, Ideally should be dependency on npm:element-resize-detector.

**Comment by MeirionHughes** [comment]
should be fixed by  6c5926467123106d3c0f3ff80d399d0161e220c4

**Comment by jimnorth55** [comment]
Will there be a new release to incorporate this commit?

**Comment by MeirionHughes** [comment]
If you're happy with it I can do, I was going to try it tonight at home before doing so.

**Comment by jimnorth55** [comment]
Was not intending to rush you... just was asking.  Please just issue the
release when you feel it is ready.
Thanks
